name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
        - 'main'
        - 'master'
        - '[0-9]+.[0-9]+.x'
    tags:

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x
