name: "Tests"

on:
    pull_request: ~
    push:
        branches:
            - master

env:
    fail-fast: true

jobs:
    test:
        name: "PHP ${{ matrix.php-version }} tests"
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: ['8.0', '8.1']

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  php-version: ${{ matrix.php-version }}

            - name: "Set composer cache directory"
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: "Cache composer"
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php-version }}-${{ matrix.symfony_constraint }}-${{ matrix.composer_option }}-composer-${{ hashFiles('composer.json') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-${{ matrix.symfony_constraint }}-${{ matrix.composer_option }}-composer-

            - name: "Cache node"
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: "Install PHP dependencies"
              run: composer update --no-progress --ansi ${{ matrix.composer_option }}

            - name: "Run tests"
              run: ./vendor/bin/phpunit
